#ifndef OSWINDOWS_H_INCLUDED
#define OSWINDOWS_H_INCLUDED
#include <windows.h>

#define SLEEP(x) Sleep(x)
#define WINDOW_CLASS "oglp"
#define WINDOW_STYLE (WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX)
#define WINDOW_STYLE_EX (WS_EX_APPWINDOW | WS_EX_WINDOWEDGE)


#endif // OSWINDOWS_H_INCLUDED
